// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    if (Platform.isWindows) {
      return windows;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjhdmfJnxr9gXjQ1gVdHQMLGcjukKnsG4',
    appId: '1:130963591290:web:277d9645ae54d43583ebc3',
    messagingSenderId: '130963591290',
    projectId: 'focusnest-39d13',
    authDomain: 'focusnest-39d13.firebaseapp.com',
    storageBucket: 'focusnest-39d13.firebasestorage.app',
    measurementId: 'G-C4BNFSBRC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9Pb0DfhWvMicwO9pwWb7JNSVjzFauag',
    appId: '1:130963591290:android:229b01ebd1dd29a683ebc3',
    messagingSenderId: '130963591290',
    projectId: 'focusnest-39d13',
    storageBucket: 'focusnest-39d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'study-buddy',
    storageBucket: 'study-buddy.appspot.com',
    iosBundleId: 'com.studybuddy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'study-buddy',
    storageBucket: 'study-buddy.appspot.com',
    iosBundleId: 'com.studybuddy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'study-buddy',
    storageBucket: 'study-buddy.appspot.com',
  );
}
